variables:
  TF_CLI_VERSION: '1.2.9'
  TERRATEST_LOG_PARSER_VERSION: '0.40.17'
  TERRATEST_TIMEOUT: '15m'
  MAJOR_MINOR_VERSION: '0.5'

include:
  - project: 'verituity/devops/cicd-templates'
    file: infra/terraform-module.yml
    ref: bugfix/terraform
    # ref: v0.4-stable
