# fail_fast: true
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
    - id: terraform_fmt
    # - id: terraform_docs
    #   args:
    #     - '--args=--lockfile=false'
    # - id: terraform_validate

# - repo: https://github.com/gruntwork-io/pre-commit
#   rev: v0.1.17
#   hooks:
#     - id: tflint
#       args:
#         - "--module"
#         - "--config=.tflint.hcl"
#     - id: terraform-validate
#     - id: terraform-fmt

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-system
      args: ["markdown", "--output-file", "README.md", "."]
    - id: terraform-docs-system
      args: ["markdown", "--output-file", "README.md", "./modules/gitlab_group"]
    - id: terraform-docs-system
      args: ["markdown", "--output-file", "README.md", "./modules/gitlab_project"]
